In [ ]:
# import pandas as pd
# # import standardScaler from sklearn.preprocessing
# from sklearn.preprocessing import StandardScaler
# itemAnalysis = pd.read_csv('figure\Item_Analysis.csv', sep=',')
# itemAnalysis.head(3)
# itemAnalysis = itemAnalysis[itemAnalysis['RIT']>0.4]
# itemAnalysis.head(3)

# itemAnalysis.rename(columns={'Unnamed: 0':'item'}, inplace=True)
# itemAnalysis.head(3)
# needItem = itemAnalysis.item.tolist()
# preExp = pd.read_csv('preExp.csv', sep=',')
# preExp = preExp[needItem]
# preExp.head(3)
# preExp.to_csv('preExpRevised.csv', index=False)

In [ ]:
# itemAnalysisRevised = pd.read_csv('figure\Item_Analysis_Revised.csv', sep=',')
# itemAnalysisRevised.head(3)

In [ ]:
# itemAnalysisRevised.to_excel('figure\Item_Analysis_Revised.xlsx', index=False)

In [1]:
import pandas as pd
import numpy as np

rawDf = pd.read_csv('preExp.csv', sep=';')
rawDf.describe()

,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,...,V43,V44,V45,V46,V47,V49,V50,V51,V52,V53
count,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,...,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000
mean,5.703125,5.463542,3.015625,4.432292,4.812500,3.510417,2.786458,3.713542,4.265625,5.130208,...,1.901042,4.265625,3.598958,4.046875,2.583333,2.625000,3.062500,2.093750,2.088542,2.036458
std,1.302591,1.417440,1.868663,1.846349,1.577409,1.807459,1.807843,1.774226,1.561066,1.662246,...,1.351981,1.970267,2.051841,1.928809,1.697961,1.719917,1.913373,1.579172,1.547663,1.579888
min,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,5.000000,4.000000,1.000000,3.000000,4.000000,2.000000,1.000000,2.000000,3.000000,4.000000,...,1.000000,3.000000,2.000000,2.750000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,6.000000,6.000000,3.000000,4.000000,5.000000,3.000000,2.000000,4.000000,4.000000,5.000000,...,1.000000,5.000000,4.000000,4.500000,2.000000,2.000000,3.000000,1.000000,1.000000,1.000000
75%,7.000000,7.000000,5.000000,6.000000,6.000000,5.000000,4.000000,5.000000,5.000000,6.000000,...,2.000000,6.000000,5.000000,6.000000,4.000000,4.000000,5.000000,3.000000,3.000000,3.000000
max,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(rawDf)
scaledDf = scaler.transform(rawDf)
scaledDf = pd.DataFrame(scaledDf, columns=rawDf.columns)
scaledDf.head(3)
# scaledDf.to_csv('preExpScaled.csv', index=False, sep=',')

In [11]:
itemAnalysis = pd.read_csv('figure\Item_Analysis.csv', sep=',')
itemAnalysis.rename(columns={'Unnamed: 0':'item'}, inplace=True)
# itemAnalysis.head(3)
itemAnalysis = itemAnalysis[itemAnalysis['RIT']>0.4]
itemAnalysis.head(3)
needItem = itemAnalysis.item.tolist()
preExpScaled = pd.read_csv('preExpScaled.csv', sep=',')
preExpScaled = preExpScaled[needItem]
preExpScaled.to_csv('preExpScaledRevised.csv', index=False)

In [11]:
temp = pd.read_csv('有恋爱经历的数据/第一轮结果/preExpScaledExperiencedRevised_afterCFA.csv', sep=';')
temp.to_csv('有恋爱经历的数据/第一轮结果/preExpScaledExperiencedRevised_afterCFA.csv', index=False, sep=',')

In [9]:
data = pd.read_excel('副本反向计分.xlsx')
scaledDf['experience'] = data['3.您是否有恋爱经历？']
preExpScaledExperienced = scaledDf[scaledDf['experience']!='A.还没有过恋爱经历']
preExpScaledExperienced.to_csv('有恋爱经历的数据\preExpScaledExperienced.csv', encoding='gb18030',index=False, sep=',')
preExpScaledExperienced = preExpScaledExperienced.drop(columns=['experience'])
preExpScaledExperienced.to_csv('有恋爱经历的数据/preExpScaledExperienced.csv', index=False, sep=',')

In [10]:
itemAnalysis = pd.read_csv('有恋爱经历的数据/第一轮结果/Item_Analysis.csv', sep=',')
itemAnalysis.rename(columns={'Unnamed: 0':'item'}, inplace=True)
# itemAnalysis.head(3)
itemAnalysis = itemAnalysis[itemAnalysis['RIT']>0.4]
itemAnalysis.head(3)
needItem = itemAnalysis.item.tolist()
preExpScaledExperienced =  preExpScaledExperienced[needItem]
preExpScaledExperienced.to_csv('有恋爱经历的数据/第一轮结果/preExpScaledExperiencedRevised.csv', index=False, sep=',')